/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiketonline;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fila sofiyati
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Halaman Daftar Akun Pembeli");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Jf_username = new javax.swing.JTextField();
        Jp_password = new javax.swing.JPasswordField();
        jButton_Register_ = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jLabelRegister = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Jf_nmdepan = new javax.swing.JTextField();
        jf_namabelakang = new javax.swing.JLabel();
        jf_nmbelakang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jp_repass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jt_email = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        lihatsandi = new javax.swing.JToggleButton();
        lihat_resandi = new javax.swing.JToggleButton();
        validasilabel = new javax.swing.JLabel();
        nmdepan = new javax.swing.JLabel();
        namabelakang = new javax.swing.JLabel();
        sandi = new javax.swing.JLabel();
        valid_email = new javax.swing.JLabel();
        mail_txt = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Nama Pengguna :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Kata Sandi           :");

        Jf_username.setBackground(new java.awt.Color(108, 122, 137));
        Jf_username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jf_username.setForeground(new java.awt.Color(228, 241, 254));
        Jf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jf_usernameActionPerformed(evt);
            }
        });

        Jp_password.setBackground(new java.awt.Color(108, 122, 137));
        Jp_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jp_password.setForeground(new java.awt.Color(228, 241, 254));
        Jp_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jp_passwordActionPerformed(evt);
            }
        });
        Jp_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Jp_passwordKeyReleased(evt);
            }
        });

        jButton_Register_.setBackground(new java.awt.Color(34, 167, 240));
        jButton_Register_.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_Register_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register_.setText("Daftar");
        jButton_Register_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Register_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Register_ActionPerformed(evt);
            }
        });

        jButton_Cancel.setBackground(new java.awt.Color(242, 38, 19));
        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cancel.setText("Batal");
        jButton_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jLabelRegister.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegister.setText("Klik disini untuk masuk");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Nama Depan       :");

        Jf_nmdepan.setBackground(new java.awt.Color(108, 122, 137));
        Jf_nmdepan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jf_nmdepan.setForeground(new java.awt.Color(228, 241, 254));
        Jf_nmdepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jf_nmdepanActionPerformed(evt);
            }
        });
        Jf_nmdepan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Jf_nmdepanKeyReleased(evt);
            }
        });

        jf_namabelakang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jf_namabelakang.setForeground(new java.awt.Color(236, 240, 241));
        jf_namabelakang.setText("Nama Belakang  :");
        jf_namabelakang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jf_namabelakangKeyReleased(evt);
            }
        });

        jf_nmbelakang.setBackground(new java.awt.Color(108, 122, 137));
        jf_nmbelakang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jf_nmbelakang.setForeground(new java.awt.Color(228, 241, 254));
        jf_nmbelakang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jf_nmbelakangActionPerformed(evt);
            }
        });
        jf_nmbelakang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jf_nmbelakangKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Ulangi Sandi        :  ");

        Jp_repass.setBackground(new java.awt.Color(108, 122, 137));
        Jp_repass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jp_repass.setForeground(new java.awt.Color(228, 241, 254));
        Jp_repass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jp_repassActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("E-mail                  :");

        Jt_email.setBackground(new java.awt.Color(108, 122, 137));
        Jt_email.setColumns(20);
        Jt_email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jt_email.setForeground(new java.awt.Color(228, 241, 254));
        Jt_email.setRows(5);
        Jt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Jt_emailKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Jt_email);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DAFTAR");

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel2)
                    .addContainerGap(534, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabelClose))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        lihatsandi.setBackground(new java.awt.Color(51, 51, 51));
        lihatsandi.setForeground(new java.awt.Color(153, 204, 255));
        lihatsandi.setText("Lihat");
        lihatsandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatsandiActionPerformed(evt);
            }
        });

        lihat_resandi.setBackground(new java.awt.Color(51, 51, 51));
        lihat_resandi.setForeground(new java.awt.Color(153, 204, 255));
        lihat_resandi.setText("Lihat");
        lihat_resandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihat_resandiActionPerformed(evt);
            }
        });

        validasilabel.setForeground(new java.awt.Color(255, 0, 51));

        nmdepan.setForeground(new java.awt.Color(255, 0, 51));
        nmdepan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nmdepanKeyReleased(evt);
            }
        });

        namabelakang.setForeground(new java.awt.Color(255, 0, 0));
        namabelakang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namabelakangKeyPressed(evt);
            }
        });

        sandi.setForeground(new java.awt.Color(255, 0, 0));

        valid_email.setForeground(new java.awt.Color(255, 0, 0));

        mail_txt.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addComponent(jf_namabelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(11, 11, 11))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(sandi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(validasilabel))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(Jp_repass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(lihat_resandi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(Jp_password, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lihatsandi)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valid_email)))
                                .addGap(0, 148, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Jf_nmdepan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nmdepan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jf_nmbelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(namabelakang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Register_)
                            .addComponent(mail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabelRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Jf_nmdepan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmdepan))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jf_namabelakang)
                    .addComponent(jf_nmbelakang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namabelakang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jp_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lihatsandi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sandi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validasilabel)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jp_repass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihat_resandi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(valid_email)
                                .addGap(17, 17, 17)
                                .addComponent(mail_txt))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Register_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 640, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked

        setVisible(false);
        dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jButton_Register_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Register_ActionPerformed
        String nm_depan = Jf_nmdepan.getText();
        String nm_belakang = jf_nmbelakang.getText();
        String uname = Jf_username.getText();
        String pass = String.valueOf(Jp_password.getPassword());
        String re_pass = String.valueOf(Jp_repass.getPassword());
        String Email = Jt_email.getText();
        
        if(!isNameValid(nm_depan) || !isNameValid(nm_belakang)) {
        JOptionPane.showMessageDialog(null, "Nama depan dan nama belakang tidak boleh mengandung karakter khusus");
        }   
        else if(uname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Masukkan username");
        }

        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Masukkan password");
        }
        else if(!pass.equals(re_pass))
        {
            JOptionPane.showMessageDialog(null, "Masukkan ulang password");
        }
        else if(Email.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Masukkan Email");
        }
        else if(checkUsername(uname))
        {
            JOptionPane.showMessageDialog(null, "Username sudah digunakan");
        }
         else if(checkEmail(Email))
        {
        JOptionPane.showMessageDialog(null, "Email sudah terdaftar sebelumnya");
        }
        else if(!isPasswordValid(pass))
        {
        JOptionPane.showMessageDialog(null, "Password harus minimal 6 karakter dengan kombinasi huruf, angka, dan karakter khusus");
        }
        else{

            PreparedStatement ps;
            String query = "INSERT INTO user(nm_depan, nm_belakang, username, password, Email) VALUES (?,?,?,?,?)";

            try {
                ps = KoneksiDB.getKoneksi().prepareStatement(query);
                ps.setString(1, nm_depan);
                ps.setString(2, nm_belakang);
                ps.setString(3, uname);
                ps.setString(4, pass);
                ps.setString(5, Email);

                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "User berhasil ditambah");
                }

            } catch (SQLException ex) {
               System.out.println("Gagal");
            }
        }
    }//GEN-LAST:event_jButton_Register_ActionPerformed
    
    private boolean isNameValid(String name) {
    String pattern = "^[a-zA-Z]+$";
    return name.matches(pattern);
    }
    private boolean checkEmail(String email) {
    PreparedStatement ps;
    ResultSet rs;
    boolean emailExists = false;
    String query = "SELECT * FROM user WHERE Email = ?";
    try {
        ps = KoneksiDB.getKoneksi().prepareStatement(query);
        ps.setString(1, email);
        rs = ps.executeQuery();
        if (rs.next()) {
            emailExists = true;
        }
    } catch (SQLException ex) {
        System.out.println("Gagal");
    }
    return emailExists;
}
    private boolean isPasswordValid(String password) {
    // Minimal 6 karakter, kombinasi huruf, angka, dan karakter khusus
    String pattern = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{6,}$";
    return password.matches(pattern);
}
    
    
    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        dispose();
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
//        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void jf_nmbelakangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jf_nmbelakangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jf_nmbelakangActionPerformed

    private void Jp_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jp_passwordActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_Jp_passwordActionPerformed

    private void Jf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jf_usernameActionPerformed

    private void Jp_repassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jp_repassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jp_repassActionPerformed

    private void Jf_nmdepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jf_nmdepanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jf_nmdepanActionPerformed

    private void lihatsandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatsandiActionPerformed
        // TODO add your handling code here:
         
        if(lihatsandi.isSelected())
            Jp_password.setEchoChar((char)0);
        else
            Jp_password.setEchoChar('*');
    }//GEN-LAST:event_lihatsandiActionPerformed

    private void lihat_resandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihat_resandiActionPerformed
        // TODO add your handling code here:
        if(lihat_resandi.isSelected())
            Jp_repass.setEchoChar((char)0);
        else
            Jp_repass.setEchoChar('*'); 
    }//GEN-LAST:event_lihat_resandiActionPerformed

    private void nmdepanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmdepanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nmdepanKeyReleased

    private void Jf_nmdepanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jf_nmdepanKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}$";
            Pattern patt=Pattern.compile(PATTERN);
            Matcher match=patt.matcher(Jf_nmdepan.getText());
            if(!match.matches()){
                nmdepan.setText("Karakter Nama tidak sesuai");
            }
            else{
                nmdepan.setText(null);
            }
    }//GEN-LAST:event_Jf_nmdepanKeyReleased

    private void jf_namabelakangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jf_namabelakangKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jf_namabelakangKeyReleased

    private void namabelakangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namabelakangKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_namabelakangKeyPressed

    private void jf_nmbelakangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jf_nmbelakangKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[a-zA-Z0-9]{0,30}$";
            Pattern patt=Pattern.compile(PATTERN);
            Matcher match=patt.matcher(jf_nmbelakang.getText());
            if(!match.matches()){
                namabelakang.setText("Karakter Nama tidak sesuai");
            }
            else{
                namabelakang.setText(null);
            }   
    }//GEN-LAST:event_jf_nmbelakangKeyReleased

    private void Jp_passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jp_passwordKeyReleased
        // TODO add your handling code here:
        String password = Jp_password.getText(); // Mengambil password dari komponen JTextField
       String regexPattern = "^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[@#$%^&+=_!])(?=\\S+$).{6,}$";

         if (Pattern.matches(regexPattern, password)) {
             sandi.setText(null);
    // Password valid, lanjutkan proses login atau registrasi
       } else {
             sandi.setText("sandi minimal 6 karakter kombinasi huruf, angka dan simbol");
    // Password tidak valid, berikan pesan kesalahan ke pengguna
       }
             /*String PATTERN = "^[a-zA-Z0-9]{0,30}[,][@][.][a-zA-Z0-9]{0,10}$";
            Pattern patt=Pattern.compile(PATTERN);
            Matcher match=patt.matcher(Jp_password.getText());
            if(!match.matches()){
                sandi.setText("sandi minimal 6 karakter kombinasi huruf, angka dan simbol");
            }
            else{
                sandi.setText(null);
            }  */  
    }//GEN-LAST:event_Jp_passwordKeyReleased

    private void Jt_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jt_emailKeyReleased
        // TODO add your handling code here:
            String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z]{0,10}[.][a-zA-Z]{0,5}$";
            Pattern patt=Pattern.compile(PATTERN);
            Matcher match=patt.matcher(Jt_email.getText());
            if(!match.matches()){
                mail_txt.setText("Email tidak sesuai");
            }
            else{
                mail_txt.setText(null);
            } 
    }//GEN-LAST:event_Jt_emailKeyReleased

    public boolean checkUsername(String username)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM user WHERE username=?";
        
        try {
            ps = KoneksiDB.getKoneksi().prepareStatement(query);
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkUser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
         return checkUser;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jf_nmdepan;
    private javax.swing.JTextField Jf_username;
    private javax.swing.JPasswordField Jp_password;
    private javax.swing.JPasswordField Jp_repass;
    private javax.swing.JTextArea Jt_email;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Register_;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jf_namabelakang;
    private javax.swing.JTextField jf_nmbelakang;
    private javax.swing.JToggleButton lihat_resandi;
    private javax.swing.JToggleButton lihatsandi;
    private javax.swing.JLabel mail_txt;
    private javax.swing.JLabel namabelakang;
    private javax.swing.JLabel nmdepan;
    private javax.swing.JLabel sandi;
    private javax.swing.JLabel valid_email;
    private javax.swing.JLabel validasilabel;
    // End of variables declaration//GEN-END:variables

   

}
