/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiketonline;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author fila sofiyati
 */
public class tampilan extends javax.swing.JFrame {
    
    Object[][] dataFilm = new Object[8][5];

    /**
     * Creates new form index
     */
    public tampilan() {
        initComponents();
        this.setLocationRelativeTo(null);// center form in the screen
        getDataFilm();
        setDataFilm();
        setTitle("Beranda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_film1 = new javax.swing.JLabel();
        lbl_film8 = new javax.swing.JLabel();
        lbl_film2 = new javax.swing.JLabel();
        lbl_film3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_judul1 = new javax.swing.JLabel();
        lbl_judul2 = new javax.swing.JLabel();
        lbl_judul3 = new javax.swing.JLabel();
        lbl_judul8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lbl_film4 = new javax.swing.JLabel();
        lbl_judul4 = new javax.swing.JLabel();
        lbl_film5 = new javax.swing.JLabel();
        lbl_judul5 = new javax.swing.JLabel();
        lbl_film6 = new javax.swing.JLabel();
        lbl_judul6 = new javax.swing.JLabel();
        lbl_film7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_judul7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cinema XXI");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jLabel22.setText("jLabel22");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Beranda");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jLabel4HierarchyChanged(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 50, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1450, -1));

        jButton1.setBackground(new java.awt.Color(225, 232, 239));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/daftar.jpg"))); // NOI18N
        jButton1.setText("Daftar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 120, -1));

        jButton2.setBackground(new java.awt.Color(227, 235, 242));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ik masuk.png"))); // NOI18N
        jButton2.setText("Masuk");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 50, 120, -1));

        lbl_film1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_film1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 160, 235));

        lbl_film8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_film8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 400, 160, 235));

        lbl_film2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_film2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 160, 235));

        lbl_film3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_film3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 160, 235));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Terbaru");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 20));

        lbl_judul1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_judul1.setText("Sewu Dino");
        lbl_judul1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_judul1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_judul1MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 90, -1));

        lbl_judul2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_judul2.setText("Jalan Yang Jauh Jangan Lupa Pulang");
        lbl_judul2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_judul2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_judul2MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_judul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 290, -1));

        lbl_judul3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_judul3.setText("Hati Suhita");
        lbl_judul3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_judul3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_judul3MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_judul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        lbl_judul8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_judul8.setText("The Little Mermaid");
        lbl_judul8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_judul8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_judul8MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_judul8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 370, -1, 20));

        jButton3.setBackground(new java.awt.Color(25, 120, 194));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Pesan Tiket");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 130, 40));

        lbl_film4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_film4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, 160, 235));

        lbl_judul4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_judul4.setText("Hello Ghost");
        lbl_judul4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_judul4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_judul4MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_judul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, -1, -1));

        lbl_film5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_film5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 160, 235));

        lbl_judul5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbl_judul5.setText("Avatar The Way Of Water");
        lbl_judul5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_judul5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_judul5MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_judul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 30));

        lbl_film6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_film6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 160, 235));

        lbl_judul6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_judul6.setText("Evil Dead Rise");
        lbl_judul6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_judul6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_judul6MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_judul6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, 30));

        lbl_film7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_film7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 165, 235));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel24.setText("CINEMA XXI 5");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Transformers Rise of The Beast");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, 30));

        lbl_judul7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Desain tanpa judul.png"))); // NOI18N
        getContentPane().add(lbl_judul7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 1260, 380));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Kembali Ke Menu Awal");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 1300, 730));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lbl_judul1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_judul1MouseClicked
        // TODO add your handling code here:
        
        Sinopsis sinopsis = new Sinopsis((String) dataFilm[0][1], (String) dataFilm[0][3], (String) dataFilm[0][2], (byte[]) dataFilm[0][4]);
        sinopsis.setVisible(true);
        
    }//GEN-LAST:event_lbl_judul1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Register rgs = new Register();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
//        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbl_judul2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_judul2MouseClicked
        // TODO add your handling code here:
        Sinopsis sinopsis = new Sinopsis((String) dataFilm[1][1], (String) dataFilm[1][3], (String) dataFilm[1][2], (byte[]) dataFilm[1][4]);
        sinopsis.setVisible(true);
                
    }//GEN-LAST:event_lbl_judul2MouseClicked

    private void lbl_judul3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_judul3MouseClicked
        // TODO add your handling code here:
         Sinopsis sinopsis = new Sinopsis((String) dataFilm[2][1], (String) dataFilm[2][3], (String) dataFilm[2][2],(byte[]) dataFilm[2][4]);
        sinopsis.setVisible(true);
    }//GEN-LAST:event_lbl_judul3MouseClicked

    private void lbl_judul8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_judul8MouseClicked
        // TODO add your handling code here:
         Sinopsis sinopsis = new Sinopsis((String) dataFilm[7][1], (String) dataFilm[7][3], (String) dataFilm[7][2],(byte[]) dataFilm[7][4]);
        sinopsis.setVisible(true);
                
               
    }//GEN-LAST:event_lbl_judul8MouseClicked

    private void jLabel4HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jLabel4HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4HierarchyChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Anda harus login dulu !");
        Login log = new Login();
        log.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lbl_judul4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_judul4MouseClicked
        // TODO add your handling code here:
         Sinopsis sinopsis = new Sinopsis((String) dataFilm[3][1], (String) dataFilm[3][3], (String) dataFilm[3][2], (byte[]) dataFilm[3][4]);
        sinopsis.setVisible(true);

    }//GEN-LAST:event_lbl_judul4MouseClicked

    private void lbl_judul5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_judul5MouseClicked
        // TODO add your handling code here:
         Sinopsis sinopsis = new Sinopsis((String) dataFilm[4][1], (String) dataFilm[4][3], (String) dataFilm[4][2],(byte[]) dataFilm[4][4]);
        sinopsis.setVisible(true);
    }//GEN-LAST:event_lbl_judul5MouseClicked

    private void lbl_judul6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_judul6MouseClicked
        // TODO add your handling code here:
         Sinopsis sinopsis = new Sinopsis((String) dataFilm[5][1], (String) dataFilm[5][3], (String) dataFilm[5][2],(byte[]) dataFilm[5][4]);
         sinopsis.setVisible(true);
    }//GEN-LAST:event_lbl_judul6MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
         Sinopsis sinopsis = new Sinopsis((String) dataFilm[6][1], (String) dataFilm[6][3], (String) dataFilm[6][2],(byte[]) dataFilm[6][4]);
        sinopsis.setVisible(true);
     
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        awal log = new awal();
        log.setVisible(true);    

    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan().setVisible(true);
            }
        });
    }
    
    private void setDataFilm() {
    lbl_judul1.setText((String) dataFilm[0][1]);
    lbl_judul2.setText((String) dataFilm[1][1]);
    lbl_judul3.setText((String) dataFilm[2][1]);
    lbl_judul4.setText((String) dataFilm[3][1]);
    lbl_judul5.setText((String) dataFilm[4][1]);
    lbl_judul6.setText((String) dataFilm[5][1]);
    lbl_judul7.setText((String) dataFilm[6][1]);
    lbl_judul8.setText((String) dataFilm[7][1]);
    
    lbl_film1.setIcon(getImageIcon((byte[]) dataFilm[0][4]));
    lbl_film2.setIcon(getImageIcon((byte[]) dataFilm[1][4]));
    lbl_film3.setIcon(getImageIcon((byte[]) dataFilm[2][4]));
    lbl_film4.setIcon(getImageIcon((byte[]) dataFilm[3][4]));
    lbl_film5.setIcon(getImageIcon((byte[]) dataFilm[4][4]));
    lbl_film6.setIcon(getImageIcon((byte[]) dataFilm[5][4]));
    lbl_film7.setIcon(getImageIcon((byte[]) dataFilm[6][4]));
    lbl_film8.setIcon(getImageIcon((byte[]) dataFilm[7][4]));
}

private ImageIcon getImageIcon(byte[] imageData) {
    if (imageData != null) {
        try {
            // Convert byte array to Image
            ByteArrayInputStream bis = new ByteArrayInputStream(imageData);
            BufferedImage bufferedImage = ImageIO.read(bis);
            
            // Create ImageIcon from BufferedImage
            return new ImageIcon(bufferedImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    // Return null or a default image icon if byte array is null or an error occurred
    return null; // or return a default image icon
}


    private void getDataFilm(){
        try {
            String sql = "SELECT * FROM pilih_film";
            Connection conn = KoneksiDB.getKoneksi();
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery(sql);
            int n = 0;
            while(rs.next()){
                dataFilm[n][0] = rs.getInt(1);
                dataFilm[n][1] = rs.getString(2);
                dataFilm[n][2] = rs.getString(3);
                dataFilm[n][3] = rs.getString(4);
                
                Blob blob = rs.getBlob(5);
                byte[] blobData = blob.getBytes(1, (int) blob.length());
                dataFilm[n][4] = blobData;
                n++;
            }
            s.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(tampilan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_film1;
    private javax.swing.JLabel lbl_film2;
    private javax.swing.JLabel lbl_film3;
    private javax.swing.JLabel lbl_film4;
    private javax.swing.JLabel lbl_film5;
    private javax.swing.JLabel lbl_film6;
    private javax.swing.JLabel lbl_film7;
    private javax.swing.JLabel lbl_film8;
    private javax.swing.JLabel lbl_judul1;
    private javax.swing.JLabel lbl_judul2;
    private javax.swing.JLabel lbl_judul3;
    private javax.swing.JLabel lbl_judul4;
    private javax.swing.JLabel lbl_judul5;
    private javax.swing.JLabel lbl_judul6;
    private javax.swing.JLabel lbl_judul7;
    private javax.swing.JLabel lbl_judul8;
    // End of variables declaration//GEN-END:variables
}
