/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiketonline;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.MediaTracker;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author fila sofiyati
 */
public class Tiket extends javax.swing.JFrame {

    /**
     * Creates new form tiket
     */
    
    String namaFilm, tanggal, waktu, jenis, kursi, kode;
    public Tiket(String namaFilm, String tanggal, String waktu, String jenis, String kursi, String kode) {
        initComponents();
        setTitle("Tampilan tiket");
        this.setLocationRelativeTo(null);
        film_tiket.setText(namaFilm);
        film2_tiket.setText(namaFilm);
        tanggal_tiket.setText(tanggal);
        tanggal2_tiket.setText(tanggal);
        waktu_tiket.setText(waktu);
        waktu2_tiket.setText(waktu);
        jenis_tiket.setText(jenis);
        jenis2_tiket.setText(jenis);
        kursi_tiket.setText(kursi);
        kursi2_tiket.setText(kursi);
        kode_tiket.setText(kode);
        kode2_tiket.setText(kode);
        if(kursi.equals("")){
            this.setVisible(false);
        } else {
            this.setVisible(true);
            
            printTiket(panelTiket);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTiket = new javax.swing.JPanel();
        kode2_tiket = new javax.swing.JLabel();
        jenis_tiket = new javax.swing.JLabel();
        jenis2_tiket = new javax.swing.JLabel();
        film_tiket = new javax.swing.JLabel();
        tanggal_tiket = new javax.swing.JLabel();
        waktu_tiket = new javax.swing.JLabel();
        kursi_tiket = new javax.swing.JLabel();
        kode_tiket = new javax.swing.JLabel();
        film2_tiket = new javax.swing.JLabel();
        tanggal2_tiket = new javax.swing.JLabel();
        waktu2_tiket = new javax.swing.JLabel();
        kursi2_tiket = new javax.swing.JLabel();
        labeldasar = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelTiket.setBackground(new java.awt.Color(255, 255, 255));
        panelTiket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kode2_tiket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kode2_tiket.setText("-");
        panelTiket.add(kode2_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 385, 130, 30));

        jenis_tiket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jenis_tiket.setText("-");
        panelTiket.add(jenis_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 160, -1));

        jenis2_tiket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jenis2_tiket.setText("-");
        panelTiket.add(jenis2_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 295, 80, 30));

        film_tiket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        film_tiket.setText("-");
        panelTiket.add(film_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 350, -1));

        tanggal_tiket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanggal_tiket.setText("-");
        panelTiket.add(tanggal_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 150, 20));

        waktu_tiket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        waktu_tiket.setText("-");
        panelTiket.add(waktu_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 170, -1));

        kursi_tiket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kursi_tiket.setText("-");
        panelTiket.add(kursi_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 170, -1));

        kode_tiket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kode_tiket.setText("-");
        panelTiket.add(kode_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 210, -1));

        film2_tiket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        film2_tiket.setText("-");
        panelTiket.add(film2_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, 20));

        tanggal2_tiket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tanggal2_tiket.setText("-");
        panelTiket.add(tanggal2_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 100, 20));

        waktu2_tiket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        waktu2_tiket.setText("-");
        panelTiket.add(waktu2_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 60, 20));

        kursi2_tiket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kursi2_tiket.setText("-");
        panelTiket.add(kursi2_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 345, 70, 20));

        labeldasar.setBackground(new java.awt.Color(255, 255, 255));
        labeldasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gbr.png"))); // NOI18N
        panelTiket.add(labeldasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTiket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void printTiket(JPanel panelYgDiPrint){
        PrinterJob job = PrinterJob.getPrinterJob() ;
        job.setJobName("print data");
        
        job.setPrintable(new java.awt.print.Printable(){
        @Override
        public int print(Graphics pg, PageFormat pf, int pageNum ){
        pf.setOrientation(PageFormat.LANDSCAPE);
        if(pageNum>0){
        return java.awt.print.Printable.NO_SUCH_PAGE;
        }
        Graphics2D g2 = (Graphics2D)pg;
        g2.translate(pf.getImageableX(), pf.getImageableY());
        g2.scale(0.47, 0.47);
        panelYgDiPrint.print(g2);
        return java.awt.print.Printable.PAGE_EXISTS;
        }       
        });
        boolean ok = job.printDialog();
        if(ok){
            try{
                job.print();
            }
            catch (PrinterException ex){
                ex.printStackTrace();
            }
        }     
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel film2_tiket;
    private javax.swing.JLabel film_tiket;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jenis2_tiket;
    private javax.swing.JLabel jenis_tiket;
    private javax.swing.JLabel kode2_tiket;
    private javax.swing.JLabel kode_tiket;
    private javax.swing.JLabel kursi2_tiket;
    private javax.swing.JLabel kursi_tiket;
    private javax.swing.JLabel labeldasar;
    public javax.swing.JPanel panelTiket;
    private javax.swing.JLabel tanggal2_tiket;
    private javax.swing.JLabel tanggal_tiket;
    private javax.swing.JLabel waktu2_tiket;
    private javax.swing.JLabel waktu_tiket;
    // End of variables declaration//GEN-END:variables
}
